# Generated by Django 5.1.7 on 2025-05-02 10:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_alter_membership_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_verification_token_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='تاریخ ایجاد توکن تأیید'),
            preserve_default=False,
        ),
    ]
