# Generated by Django 5.1.7 on 2025-05-03 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_user_failed_login_attempts_user_locked_until'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email_verification_token',
            field=models.CharField(blank=True, max_length=64, verbose_name='توکن تأیید ایمیل'),
        ),
    ]
