# Generated by Django 5.1.7 on 2025-05-03 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_alter_user_email_verification_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email_verification_token',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='توکن تأیید ایمیل'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email_verification_token_created',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ ایجاد توکن تأیید'),
        ),
    ]
