# Generated by Django 5.1.7 on 2025-05-03 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_alter_user_email_verification_token_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email_verified',
        ),
        migrations.AlterField(
            model_name='user',
            name='email_verification_token_created',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ ایجاد توکن'),
        ),
    ]
