# Generated by Django 5.1.7 on 2025-05-03 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_remove_user_email_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_verified',
            field=models.BooleanField(default=False, help_text='تعیین می\u200cکند که آیا کاربر ایمیل خود را تأیید کرده است', verbose_name='ایمیل تأیید شده'),
        ),
    ]
