# Generated by Django 5.1.7 on 2025-05-04 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_remove_user_email_verification_token_created_and_more'),
        ('university', '0002_university_city_university_province_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membership',
            options={'verbose_name': 'نقش', 'verbose_name_plural': 'نقش \u200cها'},
        ),
        migrations.AlterUniqueTogether(
            name='membership',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='membership',
            constraint=models.UniqueConstraint(condition=models.Q(('role', 'OFFI')), fields=('user', 'role'), name='unique_offi_per_user'),
        ),
    ]
