# Generated by Django 5.1.7 on 2025-05-06 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_alter_product_old_price_alter_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.CreateModel(
            name='ProductDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_description', models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='سر تیتر توضیحات کامل ')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات کامل')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descriptions', to='product.product')),
            ],
            options={
                'verbose_name': 'توضیحات محصول',
                'verbose_name_plural': 'توضیحات محصول',
            },
        ),
    ]
