# Generated by Django 5.1.7 on 2025-05-06 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_remove_product_description_productdescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdescription',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='products/main/%Y/%m/%d/', verbose_name='تصویر برای هر متن '),
        ),
    ]
