# Generated by Django 5.1.7 on 2025-05-08 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_productdescription_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='icon',
            field=models.FileField(blank=True, help_text='یک فایل SVG یا PNG برای این دسته\u200cبندی بارگذاری کنید', null=True, upload_to='category-icons/', verbose_name='آیکون دسته\u200cبندی'),
        ),
    ]
