# Generated by Django 5.1.7 on 2025-05-09 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_productcategory_icon'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productvariant',
            unique_together={('product',)},
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='color',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='material',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='size',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='stock',
        ),
    ]
