# Generated by Django 5.1.7 on 2025-05-09 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_producttype_productattribute'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductAttribute',
            new_name='ProductAttributeType',
        ),
    ]
