# Generated by Django 5.1.7 on 2025-05-09 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0022_productattributevalue'),
    ]

    operations = [
        migrations.AddField(
            model_name='productattribute',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attribute_values', to='product.product', verbose_name='محصول'),
        ),
        migrations.AddField(
            model_name='productattribute',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='تعداد'),
        ),
        migrations.AlterField(
            model_name='productattribute',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.productattributetype', verbose_name='نوع ویژگی'),
        ),
        migrations.AlterField(
            model_name='productattribute',
            name='value',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='مقدار ویژگی'),
        ),
        migrations.AlterUniqueTogether(
            name='productattribute',
            unique_together={('product', 'type', 'value')},
        ),
        migrations.DeleteModel(
            name='ProductAttributeValue',
        ),
    ]
