# Generated by Django 5.1.7 on 2025-05-09 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0024_alter_productvariant_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productattribute',
            name='quantity',
        ),
        migrations.AddField(
            model_name='productvariant',
            name='discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variants', to='product.discount'),
        ),
    ]
