# Generated by Django 5.1.7 on 2025-05-11 05:09

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0027_alter_product_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='productattribute',
            name='color',
            field=colorfield.fields.ColorField(default='#FF0000', help_text='فقط اگه مقدار ویژگی رنگ بود از این قسمت استفاده کنید', image_field=None, max_length=25, samples=None, verbose_name='رنگ به صورت استاتیک'),
        ),
    ]
