# Generated by Django 5.1.7 on 2025-05-13 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0031_alter_productattribute_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productattribute',
            name='image',
            field=models.ImageField(blank=True, help_text='اگر یه رنگ خاص دارید که داخل رنگ های اشافه شده نبود یه عکس از یه بخض از اون محصول رو اپلود کنید و اسم رنگ رو داخل فیلد مقدار ویژگی وارد کنید سپس گزینه ذخبره رو بزنید دوباره وارد همون رنگی که عکس رو وارد کردید بشید و چک کنید که رنگ مورد نظر شما با نگ انتخابی شبیه هم هستند', null=True, upload_to='images', verbose_name='رنگ به صورت عکس'),
        ),
    ]
