# Generated by Django 5.1.7 on 2025-05-13 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0032_alter_productattribute_image'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productattribute',
            unique_together={('type', 'value')},
        ),
        migrations.AlterField(
            model_name='productattribute',
            name='image',
            field=models.ImageField(blank=True, help_text='اگر یه رنگ خاص دارید که داخل رنگ های اشافه شده نبود یه عکس از یه بخش از اون محصول رو آپلود کنید و اسم رنگ رو داخل فیلد مقدار ویژگی وارد کنید سپس گزینه ذخبره رو بزنید دوباره وارد همون رنگی که عکس رو وارد کردید بشید و چک کنید که رنگ مورد نظر شما با رنگ انتخابی شبیه هم هستند', null=True, upload_to='images', verbose_name='رنگ به صورت عکس'),
        ),
        migrations.RemoveField(
            model_name='productattribute',
            name='product',
        ),
    ]
