# Generated by Django 5.1.7 on 2025-05-18 15:43

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0033_alter_productattribute_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productvariant',
            old_name='price_override',
            new_name='price',
        ),
        migrations.AlterField(
            model_name='productattribute',
            name='color',
            field=colorfield.fields.ColorField(blank=True, default='', help_text='فقط اگه مقدار ویژگی را میخواستید رنگ بزارید اول از این قسمت استفاده کنید', image_field='image', max_length=25, samples=[('#5c5ccd', 'جگری'), ('#8080f0', 'بژ تیره')], verbose_name='رنگ به صورت استاتیک'),
        ),
    ]
