# Generated by Django 5.1.7 on 2025-05-18 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0034_rename_price_override_productvariant_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='attributes',
        ),
        migrations.CreateModel(
            name='ProductVariantAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.productattribute')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variant_attributes', to='product.productvariant')),
            ],
            options={
                'verbose_name': 'ویژگی تنوع محصول',
                'verbose_name_plural': 'ویژگی\u200cهای تنوع محصول',
                'unique_together': {('variant', 'attribute')},
            },
        ),
    ]
