# Generated by Django 5.1.7 on 2025-05-18 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0035_remove_productvariant_attributes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='attributes',
            field=models.ManyToManyField(blank=True, to='product.productattribute', verbose_name='ویژگی\u200cها'),
        ),
        migrations.DeleteModel(
            name='ProductVariantAttribute',
        ),
    ]
