# Generated by Django 5.1.7 on 2025-05-18 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0036_productvariant_attributes_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productattributetype',
            options={'ordering': ['position'], 'verbose_name': 'نوع ویژگی', 'verbose_name_plural': 'انواع ویژگی\u200cها'},
        ),
        migrations.AddField(
            model_name='productattributetype',
            name='position',
            field=models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش'),
        ),
    ]
