# Generated by Django 5.1.7 on 2025-05-18 16:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('university', '0002_university_city_university_province_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivateNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('message', models.TextField(verbose_name='متن نوتیفیکیشن')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('level', models.CharField(choices=[('info', 'اطلاع'), ('warning', 'هشدار'), ('error', 'خطا')], default='info', max_length=10, verbose_name='سطح')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='گیرنده')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PublicNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('message', models.TextField(verbose_name='متن نوتیفیکیشن')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('level', models.CharField(choices=[('info', 'اطلاع'), ('warning', 'هشدار'), ('error', 'خطا')], default='info', max_length=10, verbose_name='سطح')),
                ('expire_at', models.DateTimeField(blank=True, null=True, verbose_name='انقضای نوتیفیکیشن')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.university', verbose_name='دانشگاه')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
