# Generated by Django 5.1.7 on 2025-05-19 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicnotification',
            name='university',
        ),
        migrations.DeleteModel(
            name='PrivateNotification',
        ),
        migrations.DeleteModel(
            name='PublicNotification',
        ),
    ]
