# Generated by Django 5.1.7 on 2025-05-13 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('university', '0002_university_city_university_province_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True, verbose_name='موضوع')),
                ('slug', models.SlugField(allow_unicode=True, max_length=200, unique=True, verbose_name='شناسه URL')),
            ],
            options={
                'verbose_name': 'موضوع تماس',
                'verbose_name_plural': 'موضوعات تماس',
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='نام')),
                ('last_name', models.CharField(max_length=100, verbose_name='نام\u200cخانوادگی')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='تلفن')),
                ('other_subject', models.CharField(blank=True, max_length=200, verbose_name='موضوع دیگر')),
                ('message', models.TextField(verbose_name='متن پیام')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='contact/attachments/', verbose_name='ضمیمه')),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('answered', 'پاسخ\u200cداده\u200cشده')], default='pending', max_length=10, verbose_name='وضعیت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ارسال')),
                ('responded_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ پاسخ')),
                ('university', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='university.university', verbose_name='دانشگاه')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contact.subject', verbose_name='موضوع')),
            ],
            options={
                'verbose_name': 'پیام تماس',
                'verbose_name_plural': 'پیام\u200cهای تماس',
                'ordering': ['-created_at'],
            },
        ),
    ]
