# Generated by Django 5.1.7 on 2025-05-14 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='answer',
            field=models.TextField(blank=True, null=True, verbose_name='متن پاسخ'),
        ),
    ]
