# Generated by Django 5.1.7 on 2025-05-18 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartdetail',
            old_name='Variant',
            new_name='variant',
        ),
    ]
