# Generated by Django 5.1.7 on 2025-05-19 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_rename_variant_cartdetail_variant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartdetail',
            name='final_price',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='قیمت نهایی تکی محصول'),
        ),
    ]
