# Generated by Django 5.1.7 on 2025-05-20 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_testmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestModel',
        ),
    ]
