# Generated by Django 5.1.7 on 2025-05-20 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_delete_testmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ایجاد سبد خرید'),
        ),
        migrations.AddField(
            model_name='cart',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='تاریخ تغیر در سبد خرید'),
        ),
        migrations.AddField(
            model_name='cartdetail',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ایجاد جزئیات سبد خرید'),
        ),
        migrations.AddField(
            model_name='cartdetail',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='تاریخ تغییر در جزئیات سبد خرید'),
        ),
    ]
