# Generated by Django 5.1.7 on 2025-05-20 10:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0020_adminactionlog'),
        ('cart', '0006_cart_created_at_cart_updated_at_and_more'),
        ('product', '0037_alter_productattributetype_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ثبت سفارش ')),
                ('total_price', models.PositiveIntegerField(verbose_name='مبلغ کل')),
                ('shipping_cost', models.PositiveIntegerField(default=70000)),
                ('final_price', models.PositiveIntegerField(verbose_name='مبلغ نهایی پرداختی')),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.address')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': ' سفارش ',
                'verbose_name_plural': 'لیست سفارش ها',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField()),
                ('unit_price', models.PositiveIntegerField()),
                ('total_price', models.PositiveIntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cart.order')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.product')),
                ('variant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.productvariant')),
            ],
            options={
                'verbose_name': ' جزئیات سفارش  ',
                'verbose_name_plural': 'لیست جزئیات سفارش ها',
            },
        ),
    ]
