# Generated by Django 5.1.7 on 2025-05-21 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_alter_cart_is_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'در حال انتظار تایید'), ('confirmed', 'تایید شده'), ('shipping', 'در حال ارسال به پست'), ('delivering', 'در حال ارسال پست به مقصد')], default='pending', max_length=20, verbose_name='وضعیت سفارش'),
        ),
    ]
